[tools]
python = "3.14"
"pipx" = "latest"
"pipx:pip-tools" = "latest"
ruff = "latest"

[env]
APP_ENV = "development"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[tasks.install]
alias = "requirements"
run = "pip install -r requirements.txt"

[tasks.compile]
run = "pip-compile requirements.in"

[tasks.lint]
description = "Lint the code"
run = "ruff check --fix"

[tasks.test]
description = "Run tests"
run = "pytest tests/"

[tasks.up]
run = "docker compose up -d"

[tasks.down]
run = "docker compose down"

[tasks.logs]
run = "docker compose logs -f"

[tasks.ps]
run = "docker compose ps"
